#!/usr/bin/env bash

function dmcm_run_action(){
  local func=$(dmcm_get_function $dmcm_action)

  type $func > /dev/null 2>&1

  if [[ $? -ne 0 ]]; then
    dmcm_error "Unknown function: $func"
    return 1
  fi

  $func
}
